import type { ProviderSpec } from "./types.ts";

const bearer = (key: string) => `Bearer ${key}`;

/**
 * The provider catalog. Adding support for a new backend usually means adding one
 * entry here — the adapters are keyed by `protocol`, and most services speak the
 * OpenAI-compatible protocol.
 *
 * `keyUrl` is deliberately part of the data model: the BYOK tab renders it as a
 * direct link, so an operator never has to go hunting for where keys are issued.
 * Endpoints for self-hosted software drift between versions; every one of these is
 * overridable per-install via `studio provider set-url <id> <url>`.
 */
export const PROVIDER_CATALOG: ProviderSpec[] = [
  // ---------------------------------------------------------------- local
  {
    id: "ollama",
    name: "Ollama",
    kind: "local",
    protocol: "ollama",
    capabilities: ["text", "vision", "embed"],
    baseUrl: "http://127.0.0.1:11434",
    keyUrl: "https://ollama.com/download",
    probePath: "/api/tags",
    notes: "Pull a model first, e.g. `ollama pull llama3.2`. No key required.",
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    kind: "local",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "embed"],
    baseUrl: "http://127.0.0.1:1234/v1",
    keyUrl: "https://lmstudio.ai",
    probePath: "/models",
    notes: "Enable the local server in LM Studio's Developer tab.",
  },
  {
    id: "llamacpp",
    name: "llama.cpp server",
    kind: "local",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "embed"],
    baseUrl: "http://127.0.0.1:8080/v1",
    keyUrl: "https://github.com/ggml-org/llama.cpp",
    probePath: "/models",
    notes: "Start with `llama-server -m model.gguf --port 8080`.",
  },
  {
    id: "vllm",
    name: "vLLM",
    kind: "local",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "embed"],
    baseUrl: "http://127.0.0.1:8000/v1",
    keyUrl: "https://docs.vllm.ai/en/latest/getting_started/quickstart.html",
    probePath: "/models",
    notes: "High-throughput serving; worth it once several characters tick at once.",
  },
  {
    id: "jan",
    name: "Jan",
    kind: "local",
    protocol: "openai-compatible",
    capabilities: ["text", "embed"],
    baseUrl: "http://127.0.0.1:1337/v1",
    keyUrl: "https://jan.ai",
    probePath: "/models",
  },
  {
    id: "koboldcpp",
    name: "KoboldCpp",
    kind: "local",
    protocol: "openai-compatible",
    capabilities: ["text"],
    baseUrl: "http://127.0.0.1:5001/v1",
    keyUrl: "https://github.com/LostRuins/koboldcpp",
    probePath: "/models",
  },
  {
    id: "textgen-webui",
    name: "Text Generation WebUI",
    kind: "local",
    protocol: "openai-compatible",
    capabilities: ["text"],
    baseUrl: "http://127.0.0.1:5000/v1",
    keyUrl: "https://github.com/oobabooga/text-generation-webui",
    probePath: "/models",
    notes: "Launch with `--api` to expose the OpenAI-compatible endpoint.",
  },
  {
    id: "comfyui",
    name: "ComfyUI",
    kind: "local",
    protocol: "custom",
    capabilities: ["image", "video"],
    baseUrl: "http://127.0.0.1:8188",
    keyUrl: "https://github.com/comfyanonymous/ComfyUI",
    probePath: "/system_stats",
    notes: "Local image/video generation. Asset jobs post a workflow graph to /prompt.",
  },

  // ---------------------------------------------------------------- cloud
  {
    id: "higgsfield",
    name: "Higgsfield",
    kind: "cloud",
    protocol: "custom",
    capabilities: ["image", "video", "audio", "mesh3d"],
    baseUrl: "https://platform.higgsfield.ai",
    keyUrl: "https://cloud.higgsfield.ai",
    envVar: "HIGGSFIELD_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    notes:
      "Motion-control video, image and 3D generation. Also reachable through the " +
      "Higgsfield MCP server when running inside an MCP-capable client.",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    kind: "cloud",
    protocol: "anthropic",
    capabilities: ["text", "vision"],
    baseUrl: "https://api.anthropic.com/v1",
    keyUrl: "https://console.anthropic.com/settings/keys",
    envVar: "ANTHROPIC_API_KEY",
    authHeader: "x-api-key",
    authScheme: (k) => k,
    probePath: "/models",
  },
  {
    id: "openai",
    name: "OpenAI",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "embed", "image", "audio", "voice"],
    baseUrl: "https://api.openai.com/v1",
    keyUrl: "https://platform.openai.com/api-keys",
    envVar: "OPENAI_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "google",
    name: "Google AI Studio",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "embed", "image", "video"],
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    keyUrl: "https://aistudio.google.com/apikey",
    envVar: "GEMINI_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "vision"],
    baseUrl: "https://openrouter.ai/api/v1",
    keyUrl: "https://openrouter.ai/keys",
    envVar: "OPENROUTER_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
    notes: "One key fronting many model vendors; useful as a fallback route.",
  },
  {
    id: "groq",
    name: "Groq",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "audio"],
    baseUrl: "https://api.groq.com/openai/v1",
    keyUrl: "https://console.groq.com/keys",
    envVar: "GROQ_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "together",
    name: "Together AI",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "embed", "image"],
    baseUrl: "https://api.together.xyz/v1",
    keyUrl: "https://api.together.xyz/settings/api-keys",
    envVar: "TOGETHER_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "image"],
    baseUrl: "https://api.fireworks.ai/inference/v1",
    keyUrl: "https://fireworks.ai/account/api-keys",
    envVar: "FIREWORKS_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "mistral",
    name: "Mistral",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "embed"],
    baseUrl: "https://api.mistral.ai/v1",
    keyUrl: "https://console.mistral.ai/api-keys",
    envVar: "MISTRAL_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text"],
    baseUrl: "https://api.deepseek.com/v1",
    keyUrl: "https://platform.deepseek.com/api_keys",
    envVar: "DEEPSEEK_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "xai",
    name: "xAI",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "vision", "image"],
    baseUrl: "https://api.x.ai/v1",
    keyUrl: "https://console.x.ai",
    envVar: "XAI_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text"],
    baseUrl: "https://api.cerebras.ai/v1",
    keyUrl: "https://cloud.cerebras.ai",
    envVar: "CEREBRAS_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    kind: "cloud",
    protocol: "custom",
    capabilities: ["audio", "voice"],
    baseUrl: "https://api.elevenlabs.io/v1",
    keyUrl: "https://elevenlabs.io/app/settings/api-keys",
    envVar: "ELEVENLABS_API_KEY",
    authHeader: "xi-api-key",
    authScheme: (k) => k,
    probePath: "/voices",
    notes: "Voice synthesis. Cloning a real person's voice requires their consent.",
  },
  {
    id: "replicate",
    name: "Replicate",
    kind: "cloud",
    protocol: "custom",
    capabilities: ["image", "video", "audio", "mesh3d"],
    baseUrl: "https://api.replicate.com/v1",
    keyUrl: "https://replicate.com/account/api-tokens",
    envVar: "REPLICATE_API_TOKEN",
    authHeader: "Authorization",
    authScheme: (k) => `Token ${k}`,
    probePath: "/models",
  },
  {
    id: "fal",
    name: "fal.ai",
    kind: "cloud",
    protocol: "custom",
    capabilities: ["image", "video", "audio", "mesh3d"],
    baseUrl: "https://fal.run",
    keyUrl: "https://fal.ai/dashboard/keys",
    envVar: "FAL_KEY",
    authHeader: "Authorization",
    authScheme: (k) => `Key ${k}`,
  },
  {
    id: "stability",
    name: "Stability AI",
    kind: "cloud",
    protocol: "custom",
    capabilities: ["image", "video", "mesh3d"],
    baseUrl: "https://api.stability.ai/v2beta",
    keyUrl: "https://platform.stability.ai/account/keys",
    envVar: "STABILITY_API_KEY",
    authHeader: "Authorization",
    authScheme: bearer,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    kind: "cloud",
    protocol: "openai-compatible",
    capabilities: ["text", "image", "embed"],
    baseUrl: "https://router.huggingface.co/v1",
    keyUrl: "https://huggingface.co/settings/tokens",
    envVar: "HF_TOKEN",
    authHeader: "Authorization",
    authScheme: bearer,
    probePath: "/models",
  },
];

export function findProvider(id: string): ProviderSpec | undefined {
  return PROVIDER_CATALOG.find((p) => p.id === id);
}

export function requireProvider(id: string): ProviderSpec {
  const spec = findProvider(id);
  if (!spec) {
    throw new Error(
      `Unknown provider "${id}". Known: ${PROVIDER_CATALOG.map((p) => p.id).join(", ")}`,
    );
  }
  return spec;
}
